spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/spring-ecommerce?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none